const plugin = require("tailwindcss/plugin");

module.exports = {
  plugins: [
    plugin(function ({ addComponents }) {
      addComponents({
        ".btn-primary": {
          position: "relative",
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
          gap: "0.5rem",
          padding: "1rem 1.75rem",
          fontSize: "1rem",
          borderRadius: "0.75rem",
          fontWeight: "700",
          color: "white",
          background:
            "linear-gradient(to right, var(--color-primary), rgb(168 85 247))",
          boxShadow: "0 10px 15px -3px rgb(139 92 246 / 0.3)",
          transition: "all 0.2s",
          "&:hover": {
            boxShadow: "0 20px 25px -5px rgb(139 92 246 / 0.5)",
            transform: "scale(1.02)",
          },
          "&:focus": {
            outline: "none",
            boxShadow: "0 0 0 2px rgb(139 92 246 / 0.5)",
          },
        },
        ".btn-accent": {
          position: "relative",
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
          gap: "0.5rem",
          padding: "1rem 1.75rem",
          fontSize: "1rem",
          borderRadius: "0.75rem",
          fontWeight: "700",
          color: "white",
          background:
            "linear-gradient(to right, var(--color-accent), rgb(6 182 212))",
          boxShadow: "0 10px 15px -3px rgb(6 182 212 / 0.3)",
          transition: "all 0.2s",
          "&:hover": {
            boxShadow: "0 20px 25px -5px rgb(6 182 212 / 0.5)",
            transform: "scale(1.02)",
          },
        },
        ".btn-secondary": {
          position: "relative",
          display: "inline-flex",
          alignItems: "center",
          justifyContent: "center",
          gap: "0.5rem",
          padding: "1rem 1.75rem",
          fontSize: "1rem",
          borderRadius: "0.75rem",
          fontWeight: "700",
          color: "var(--color-text)",
          backgroundColor: "var(--color-card)",
          border: "2px solid var(--color-border)",
          transition: "all 0.2s",
          "&:hover": {
            borderColor: "rgb(139 92 246 / 0.6)",
            backgroundColor: "rgb(26 26 26 / 0.8)",
          },
        },
        ".input-glass": {
          width: "100%",
          padding: "1.25rem 1.5rem",
          fontSize: "1.125rem",
          lineHeight: "1.75rem",
          borderRadius: "0.875rem",
          backgroundColor: "rgb(26 26 26 / 0.9)",
          backdropFilter: "blur(8px)",
          color: "white",
          border: "2px solid var(--color-border)",
          fontWeight: "500",
          transition: "all 0.2s",
          minHeight: "3.5rem",
          "&::placeholder": {
            color: "rgb(156 163 175 / 0.8)",
            fontSize: "1rem",
          },
          "&:hover": {
            borderColor: "rgb(139 92 246 / 0.4)",
            backgroundColor: "rgb(26 26 26 / 0.95)",
          },
          "&:focus": {
            outline: "none",
            borderColor: "var(--color-primary)",
            boxShadow: "0 0 0 4px rgb(139 92 246 / 0.25)",
            backgroundColor: "rgb(26 26 26 / 1)",
          },
        },
        ".glass-panel": {
          position: "relative",
          backgroundColor: "rgb(26 26 26 / 0.95)",
          backdropFilter: "blur(24px)",
          border: "1px solid var(--color-border)",
          borderRadius: "1rem",
          boxShadow: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
        },
        ".card-product": {
          position: "relative",
          backgroundColor: "rgb(26 26 26 / 0.95)",
          backdropFilter: "blur(24px)",
          border: "1px solid var(--color-border)",
          borderRadius: "1rem",
          boxShadow: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
          padding: "1.5rem",
          cursor: "pointer",
          transition: "all 0.3s",
          "&:hover": {
            borderColor: "rgb(139 92 246 / 0.5)",
            boxShadow: "0 25px 50px -12px rgb(139 92 246 / 0.1)",
            transform: "translateY(-4px)",
          },
        },
        ".feature-card": {
          position: "relative",
          backgroundColor: "rgb(26 26 26 / 0.95)",
          backdropFilter: "blur(24px)",
          border: "1px solid var(--color-border)",
          borderRadius: "1rem",
          boxShadow: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
          padding: "2rem",
          textAlign: "center",
          transition: "all 0.3s",
          "&:hover": {
            borderColor: "rgb(139 92 246 / 0.3)",
            transform: "translateY(-6px)",
          },
        },
        ".link-primary": {
          color: "var(--color-primary)",
          textUnderlineOffset: "4px",
          transition: "all 0.2s",
          "&:hover": {
            color: "rgb(139 92 246 / 0.8)",
            textDecoration: "underline",
          },
        },
        ".link-accent": {
          color: "var(--color-accent)",
          textUnderlineOffset: "4px",
          transition: "all 0.2s",
          "&:hover": {
            color: "rgb(6 182 212 / 0.8)",
            textDecoration: "underline",
          },
        },
        ".card-title": {
          marginTop: "0.75rem",
          fontSize: "1.25rem",
          fontWeight: "700",
          color: "white",
        },
        ".card-meta": {
          marginTop: "0.5rem",
          fontSize: "0.875rem",
          color: "var(--color-muted)",
        },
        ".badge": {
          display: "inline-flex",
          alignItems: "center",
          padding: "0.25rem 0.75rem",
          borderRadius: "9999px",
          fontSize: "0.75rem",
          fontWeight: "600",
          backgroundColor: "rgb(139 92 246 / 0.2)",
          color: "var(--color-primary)",
          border: "1px solid rgb(139 92 246 / 0.3)",
        },
      });
    }),
  ],
};
